name: bash_env shell checker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check syntax script user_defined_functions
        id: syntax_checker_user_defined_functions
        run: |
          bash -n user_defined_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_str_functions
        id: syntax_checker_user_defined_str_functions
        run: |
          bash -n user_defined_str_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_file_functions
        id: syntax_checker_user_defined_file_functions
        run: |
          bash -n user_defined_file_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_hw_functions
        id: syntax_checker_user_defined_hw_functions
        run: |
          bash -n user_defined_hw_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_net_functions
        id: syntax_checker_user_defined_net_functions
        run: |
          bash -n user_defined_net_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_py_functions
        id: syntax_checker_user_defined_py_functions
        run: |
          bash -n user_defined_py_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_perl_functions
        id: syntax_checker_user_defined_perl_functions
        run: |
          bash -n user_defined_perl_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_java_functions
        id: syntax_checker_user_defined_java_functions
        run: |
          bash -n user_defined_java_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_embedded_functions
        id: syntax_checker_user_defined_embedded_functions
        run: |
          bash -n user_defined_embedded_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_web_functions
        id: syntax_checker_user_defined_web_functions
        run: |
          bash -n user_defined_web_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_git_functions
        id: syntax_checker_user_defined_git_functions
        run: |
          bash -n user_defined_git_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check syntax script user_defined_doc_functions
        id: syntax_checker_user_defined_doc_functions
        run: |
          bash -n user_defined_doc_functions && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check size script user_defined_functions
        id: size_checker_user_defined_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_str_functions
        id: size_checker_user_defined_str_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_str_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_file_functions
        id: size_checker_user_defined_file_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_file_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_hw_functions
        id: size_checker_user_defined_hw_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_hw_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_net_functions
        id: size_checker_user_defined_net_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_net_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_py_functions
        id: size_checker_user_defined_py_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_py_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_perl_functions
        id: size_checker_user_defined_perl_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_perl_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_java_functions
        id: size_checker_user_defined_java_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_java_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_embedded_functions
        id: size_checker_user_defined_embedded_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_embedded_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_web_functions
        id: size_checker_user_defined_web_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_web_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_git_functions
        id: size_checker_user_defined_git_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_git_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check size script user_defined_doc_functions
        id: size_checker_user_defined_doc_functions
        run: |
          echo Checking size
          code_line_number=$(wc -l < user_defined_doc_functions)
          [[ $code_line_number -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check on failures user_defined_functions
        if: steps.syntax_checker_user_defined_functions.outputs.status == 'failure' || steps.size_checker_user_defined_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_str_functions
        if: steps.syntax_checker_user_defined_str_functions.outputs.status == 'failure' || steps.size_checker_user_defined_str_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_hw_functions
        if: steps.syntax_checker_user_defined_hw_functions.outputs.status == 'failure' || steps.size_checker_user_defined_hw_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_py_functions
        if: steps.syntax_checker_user_defined_py_functions.outputs.status == 'failure' || steps.size_checker_user_defined_py_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_perl_functions
        if: steps.syntax_checker_user_defined_perl_functions.outputs.status == 'failure' || steps.size_checker_user_defined_perl_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_java_functions
        if: steps.syntax_checker_user_defined_java_functions.outputs.status == 'failure' || steps.size_checker_user_defined_java_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_embedded_functions
        if: steps.syntax_checker_user_defined_embedded_functions.outputs.status == 'failure' || steps.size_checker_user_defined_embedded_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_web_functions
        if: steps.syntax_checker_user_defined_web_functions.outputs.status == 'failure' || steps.size_checker_user_defined_web_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_git_functions
        if: steps.syntax_checker_user_defined_git_functions.outputs.status == 'failure' || steps.size_checker_user_defined_git_functions.outputs.status == 'failure'
        run: exit 1
      - name: Check on failures user_defined_doc_functions
        if: steps.syntax_checker_user_defined_doc_functions.outputs.status == 'failure' || steps.size_checker_user_defined_doc_functions.outputs.status == 'failure'
        run: exit 1
